### ISSUE TITLE
Insuline formule in C#

### ISSUE THREAD

**Issue by RipOrbofWinter** [RipOrbofWinter/DiabetesApp#24]
### Issue:
Oplossen & Injecteren: 
https://dtc.ucsf.edu/types-of-diabetes/type2/treatment-of-type-2-diabetes/medications-and-therapies/type-2-insulin-rx/calculating-insulin-dose/

We hebben een formule ontvangen van Philips waarmee we de insuline gehalte van een patient kunnen bereken. Hieruit kunnen we een advies geven over 

Functie:
KH-ratio = koolhydraten / insuline eenheden 

### To Do:

- [x] Ingeven data
- [x] Berekenen van de formule
- [x] Teruggeven insuline advies 
- [x] Maken van unit tests
- [ ] Exception handling

**Comment by MickeyKrekels** [comment]
Formules Insulin and Unit testing is done for C#
